export type ColorTypes =
  | 'transparent'
  | 'current'
  | 'primary'
  | 'secondary'
  | 'tertiary'
  | 'quaternary'
  | 'quinary'
  | 'senary'
export type TextSizeTypes =
  | 'xs'
  | 'sm'
  | 'base'
  | 'lg'
  | 'xl'
  | '2xl'
  | '3xl'
  | '4xl'
  | '5xl'
  | '6xl'
  | '7xl'
  | '8xl'
  | '9xl'
export type TextTransformTypes =
  | 'uppercase'
  | 'lowercase'
  | 'capitalize'
  | 'normal-case'
export type TextDecorationTypes =
  | 'underline'
  | 'overline'
  | 'line-through'
  | 'no-underline'
export type FontWeightTypes =
  | 'thin'
  | 'extralight'
  | 'light'
  | 'normal'
  | 'medium'
  | 'semibold'
  | 'bold'
  | 'extrabold'
  | 'black'
export type IconsList = 'export' | 'import' | 'undo'
